#!/bin/bash

URL="https://github.com/tuimac/totp_linux.git"
USERNAME="tuimac"
PASSWORD="night99)"

[[ ! -e .git ]] && git init

[[ $1 == "" ]] && { echo "Select files"; exit 1; }

git add "$1"

echo -en "Comment below\n> "
read COMMENT

git commit -m "${COMMENT}"
git remote add origin "${URL}"

#echo -en "Type in branch(Empty is master)\n> "
#read BRANCH
#[[ $BRANCH == "" ]] && BRANCH="master"
#git push -u origin "${BRANCH}"

expect -c "
set timeout 5
spawn git push -u origin master
expect \"Username*\"
send -- \"${USERNAME}\n\"
expect \"Password*\"
send -- \"${PASSWORD}\n\"
"
