#!/bin/bash

[[ ! -e .git ]] && git init

[[ $1 == "" ]] && { echo "Select files"; exit 1; }

git add "$1"

echo -en "Comment below\n> "
read COMMENT

git commit -m "${COMMENT}"
git remote add origin

#echo -en "Type in branch(Empty is master)\n> "
#read BRANCH
#[[ $BRANCH == "" ]] && BRANCH="master"
#git push -u origin "${BRANCH}"

git push -u origin master
